### ISSUE TITLE
How to use the plugin in a build process

### ISSUE THREAD

**Issue by DanielKuehner** [jeffskj/cd-versions-maven-plugin#1]
Hi Jeff,

perhaps I am too new to maven but I cannot image how to use your plugin in the correct way. I understand that it creates a new POM. But how do I execute the new POM? Especially in the build/CI process. Do I have to build it twice? But the first run did already build the project!

It would be very kind if you can light out more (here or in your readme) how it all works together.

Thank you, Daniel

**Comment by jeffskj** [comment]
You would either run the deploy lifecycle goal or have jenkins upload the pom. The reason for the generated pom to be named release.pom and in the root directory is actually because jenkins will only upload poms named either pom.xml or *.pom. This plugin replaces the file in the MavenProject in the reactor so the deploy plugin works fine and uploads the generated pom file and jenkins will as well. Basically if you setup your pom like the readme you shouldn't have to do anything different

**Comment by DanielKuehner** [comment]
I just have added the plugin to my build section and runned mvn package from within my IDE. The only thing what happend was that the release.pom was created. The console output and the manifest/pom within the resulting jar still have the variables inside - not the final version.

So what do I not understand?

**Comment by jeffskj** [comment]
Did you pass the property you are wanting to substitute on the command line? You have to run it with `-Drevision=1.2.3` or whatever. You can also specify a default as a property in the pom in the `<properties>` section.

**Comment by DanielKuehner** [comment]
No - as your readme does not tell me to do this. Perhaps you can add this to the readme.

And now I know where _my_ problem is. I am using the https://github.com/ktoso/maven-git-commit-id-plugin with which I am determing the version parts during the maven build. So I have nothing to pass as you are suggesting. I think I was completly thinking in another direction as I found your post https://stackoverflow.com/a/28776404/3162415. I am sorry for the confusion.

In parallel I have continued to research my problem and I might have found the solution with https://github.com/pascalgn/properties-maven-extension - which describes my usecase. I have not tested it yet - but perhaps this might also be useful for you.

I am really sorry to have bother you.

**Comment by jeffskj** [comment]
I'll update the readme to add a little more usage information. The way we use it is by having jenkins pass the system property using the environment variables available from jenkins. So we pass `-Drevision=${BUILD_NUMBER}-${GIT_REVISION}`. 

The properties maven extension looks like it could also work for you.

**Comment by jeffskj** [comment]
FYI, I updated the readme,

**Comment by DanielKuehner** [comment]
Thank you :-)
